<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-08-12 17:00

$extensionPath = t3lib_extMgm::extPath('workspaces_performance');
$extensionClassesPath = $extensionPath . 'classes/';
return array(
	'tx_workspacesperformance_configuration_backendconfigurationmanager' => $extensionClassesPath . 'Configuration&/BackendConfigurationManager.php',
	'tx_workspacesperformance_utility_pageutility' => $extensionClassesPath . 'Utility/PageUtility.php',
	'tx_workspacesperformance_utility_sortutility' => $extensionClassesPath . 'Utility/SortUtility.php',
	'tx_workspacesperformance_utility_stageutility' => $extensionClassesPath . 'Utility/StageUtility.php',
	'tx_workspacesperformance_utility_workspaceutility' => $extensionClassesPath . 'Utility/WorkspaceUtility.php',
	'tx_workspacesperformance_bootstrap' => $extensionClassesPath . 'Bootstrap.php',
);
?>